### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by jmhaining** [jmhaining/MSD-P21422-BSF#4]
Bad news: Looks like one of the times SSH was enabled on the RPi, crypto mining malware was installed as evidenced by a "zmap" program driving CPU usage up. zmap was removed, but there's a hidden script somewhere that is resetting the password every time the RPi boots so my changes to the password aren't sticking. Thankfully the RPi automatically logs into the root user at boot.

Unless we can find the script or some other way to stop it, everywhere else on the internet says the SD card will need to be reflashed. I'm going to look into finding an alternate solution before reflashing, but in the meantime backups of important files will need to be made to ensure work can continue smoothly.

**Comment by jnoble157** [comment]
Nice find... I've been wondering why the CPU usage was running so high.

I have an SD card adapter I'll bring to the lab Thursday if you're unable to find the hidden script. Although it may be a good idea to do a clean flash either way.

**Comment by jmhaining** [comment]
Couldn't find the script, so I reflashed the card. I'll monitor it for another few days before I close this issue to make sure there are no other lingering problems.
